### PR TITLE
Add support for `WINEPREFIX` variable usage.

### PR DESCRIPTION
**Pull request by denisfa**
Hey,

sorry for not opening an issue first, but this seems like a rather simple change. So I decided to do it directly as a pr.

Context: you can change the default wineprefix by using this variable. The file `wine-browsedrive.desktop` had it hard-coded to its default location (`.wine/dosdevices/c:`). Some people, like myself, set this variable on `.profile` just to avoid clutter the `$HOME` dir.

@clefebvre (tagged you because of `git blame`. Apologies if it is not the right person).

### CODE REVIEW

**Comment by mtwebster** [comment]
Hi, how were you launching this? It doesn't work (at least from Cinnamon's menu and double-clicking the desktop file from nemo) - however, changing it to this resolves it: `sh -c 'xdg-open "${WINEPREFIX:-${HOME}}/.wine/dosdevices/c:"'`

 - Single quotes won't expand variables - you end up with:
```
gio: file:///home/mtwebster/$%7BWINEPREFIX:-$%7BHOME%7D%7D/.wine/dosdevices/c:: Error when getting information for file “/home/mtwebster/${WINEPREFIX:-${HOME}}/.wine/dosdevices/c:”: No such file or directory
```
- The final closing wavy bracket needs to be before the remaining path.

Thanks

**Comment by denisfa** [comment]
@mtwebster Thank you for the answer. You are correct. I messed up and pushed the wrong branch. I updated this one now with the latest changes. It contains the fix, as you suggested.

About testing, I had this one checked using `gio launch wine-browsedrive.desktop` and clicking the corresponding icon on `xfce4-whiskermenu-plugin=2.5.3`.

Just a heads up in case this can matter: as far as shell goes, I tested this with `bash=5.1.8`, `dash=0.5.11`, `zsh=5.8` (correct). I tried with `fish=3.3.1`, but it has no support for the syntactic sugar used here [(variable default value)](https://github.com/fish-shell/fish-shell/issues/2504). 

Not sure if/when this will be added. This might be annoying for some users.

**Comment by denisfa** [comment]
Hey, an update on this. I have been doing some research and found a way to write in a POSIX-compliant way (should work on all shells - as it does with the previous + fish):
```bash
[ "$WINEPREFIX" = '' ] && xdg-open "$HOME"/.wine/dosdevices/c: || [ "$WINEPREFIX" != '' ] && xdg-open "$WINEPREFIX"/dosdevices/c:
```

for the `.desktop` file:
```
....
Exec=sh -c "[ \"\\$WINEPREFIX\" = '' ] && xdg-open \"\\$HOME\"/.wine/dosdevices/c: || [ \"\\$WINEPREFIX\" != '' ] && xdg-open \"\\$WINEPREFIX\"/dosdevices/c:"
...
```

This looks really ugly, though. I will try to improve it.

**Comment by denisfa** [comment]
Another update here: my previous comment is wrong: the code does not work and we don't need to think about other shells at all.

`xdg-open` itself is written in a posix compliant way; it uses `!/bin/sh` to execute. If this tool assumes `sh` is available, then we can safely use it as well. I made more clear on the code with the full path. Therefore, we should be able to use the syntax sugar presented there. 

@mtwebster Sorry for the delay and keeping this open for this long, but I believe now it should be ready.

**Pull request merged**
